name: rahisi_agro_pay
description: "The official financial and agribusiness platform for Oletai Agro Group LTD."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.10.7

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # UI and API dependencies
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  
  # --- NEW: QR CODE ECOSYSTEM ---
  qr_flutter: ^4.1.0        # Generates the QR codes for the Agrovets
  mobile_scanner: ^6.0.0    # Allows the Farmer to scan the QR codes
  fl_chart: ^1.1.1
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints.
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1   # Generates the App Icon
  flutter_native_splash: ^2.3.6     # Generates the Splash Screen

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is included.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/oletai_logo.png 

# ==========================================
# APP ICON CONFIGURATION
# ==========================================
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/oletai_logo.png" 
  min_sdk_android: 21

# ==========================================
# NATIVE SPLASH SCREEN CONFIGURATION
# ==========================================
flutter_native_splash:
  color: "#0C462B" 
  image: "assets/images/oletai_logo.png"
  android_12:
    color: "#0C462B"
    image: "assets/images/oletai_logo.png"